console.log('João nasceu em 1984.')
console.log('Em 2000, João conheceu Maria.')
console.log('João casou-se com Maria 2012.')
console.log('Maria teve um filho de João em 2015')
console.log('O filho de João se chama Eduardo.')
